apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ez-frame-generator-scaledobject
spec:
  scaleTargetRef:
    name: ez-frame-generator-ms
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/637423288778/video-processing-queue
        queueLength: "2"           # Escala 1 pod a cada 2 msgs pendentes
        awsRegion: us-east-1
      authenticationRef:
        name: keda-aws-auth
